# Makefile: Ubuntu Autoinstall ISO Builder & Cloud-Init VFAT Floppy (cidata.img)

VERSION := 26.04
ISO := ubuntu-$(VERSION)-live-server-amd64.iso
ISO_URL := https://releases.ubuntu.com/$(VERSION)/$(ISO)
ISODIR := ubuntu-$(VERSION)-autoinstall
NEWISO := $(ISODIR).iso
PROJECT_HOME := $(CURDIR)
USER_DATA ?= user-data.yml
META_DATA ?= meta-data.yml

CIDATA := cidata.img

SRC        := $(ISODIR)/source-files
PATCHSTAMP := $(ISODIR)/.patched

MARK_BEGIN := UBUNTU-AUTOINSTALL-MENU-BEGIN
MARK_END   := UBUNTU-AUTOINSTALL-MENU-END

ISO_DEPS  := curl 7z xorriso
SEED_DEPS := mkfs.vfat mount umount dd fsck.fat

.PHONY: all check-deps check-files clean distclean download extract addfiles \
        patch cidata

.NOTPARALLEL:

all: check-deps check-files $(NEWISO)

check-deps:
	@for dep in $(ISO_DEPS); do \
		command -v $$dep >/dev/null 2>&1 || { echo "'$$dep' is not installed"; exit 1; }; \
	done

check-files:
	@test -f "$(META_DATA)" || { echo "Missing $(META_DATA)"; exit 1; }
	@test -f "$(USER_DATA)" || { echo "Missing $(USER_DATA)"; exit 1; }
	@test -f grub-autoinstall.menu || { echo "Missing grub-autoinstall.menu"; exit 1; }

download: $(ISO)
$(ISO):
	curl -C - --remote-time -o "$@" "$(ISO_URL)"

extract: $(SRC)/boot/grub/grub.cfg

$(SRC)/boot/grub/grub.cfg: $(ISO)
	rm -rf $(ISODIR)
	mkdir -p $(SRC)
	cd $(ISODIR) && 7z x -y "$(PROJECT_HOME)/$(ISO)" -osource-files
	@if [ -d $(SRC)/\[BOOT\] ]; then mv $(SRC)/\[BOOT\] $(ISODIR)/BOOT; fi
	test -f $(SRC)/boot/grub/grub.cfg
	test -f $(SRC)/boot/grub/i386-pc/eltorito.img
	test -f $(ISODIR)/BOOT/1-Boot-NoEmul.img
	test -f $(ISODIR)/BOOT/2-Boot-NoEmul.img
	test -d $(SRC)/casper

addfiles: $(SRC)/server/user-data $(SRC)/server/meta-data

$(SRC)/server/user-data: $(USER_DATA) | $(SRC)/boot/grub/grub.cfg
	mkdir -p $(SRC)/server
	cp -p "$(USER_DATA)" $(SRC)/server/user-data

$(SRC)/server/meta-data: $(META_DATA) | $(SRC)/boot/grub/grub.cfg
	mkdir -p $(SRC)/server
	cp -p "$(META_DATA)" $(SRC)/server/meta-data

patch: $(PATCHSTAMP)

$(PATCHSTAMP): grub-autoinstall.menu $(SRC)/boot/grub/grub.cfg
	@GRUB_CFG="$(SRC)/boot/grub/grub.cfg"; \
	MENU_IN="$(PROJECT_HOME)/grub-autoinstall.menu"; \
	sed -i "/$(MARK_BEGIN)/,/$(MARK_END)/d" "$$GRUB_CFG"; \
	FIRST_ENTRY=$$(grep -n -m1 '^menuentry' "$$GRUB_CFG" | cut -d: -f1); \
	[ -n "$$FIRST_ENTRY" ] || FIRST_ENTRY=$$(grep -n -m1 '^[[:space:]]*menuentry' "$$GRUB_CFG" | cut -d: -f1); \
	test -n "$$FIRST_ENTRY" || { echo "No menuentry found in $$GRUB_CFG -- refusing to patch"; exit 1; }; \
	head -n $$((FIRST_ENTRY - 1)) "$$GRUB_CFG" > "$$GRUB_CFG.new"; \
	echo "# $(MARK_BEGIN) -- generated by 'make patch'; edits are overwritten" >> "$$GRUB_CFG.new"; \
	cat "$$MENU_IN" >> "$$GRUB_CFG.new"; \
	echo "# $(MARK_END)" >> "$$GRUB_CFG.new"; \
	tail -n +$$FIRST_ENTRY "$$GRUB_CFG" >> "$$GRUB_CFG.new"; \
	mv "$$GRUB_CFG.new" "$$GRUB_CFG"; \
	sed -i 's|^set default=.*|set default="0"|' "$$GRUB_CFG"; \
	echo "Patched GRUB menu: $$GRUB_CFG"
	@touch $@

grub-autoinstall.menu:
	@echo "Please create a grub-autoinstall.menu file with your custom GRUB menu entries." ; exit 1

$(NEWISO): $(PATCHSTAMP) $(SRC)/server/user-data $(SRC)/server/meta-data
	rm -f "$(PROJECT_HOME)/$(NEWISO)"
	cd $(SRC) && xorriso -as mkisofs -r \
		-V "Ubuntu-Server $(VERSION) LTS AUTO" \
		-o "$(PROJECT_HOME)/$(NEWISO)" \
		--grub2-mbr ../BOOT/1-Boot-NoEmul.img \
		-partition_offset 16 \
		--mbr-force-bootable \
		-append_partition 2 28732ac11ff8d211ba4b00a0c93ec93b ../BOOT/2-Boot-NoEmul.img \
		-appended_part_as_gpt \
		-iso_mbr_part_type a2a0d0ebe5b9334487c068b6b72699c7 \
		-c /boot.catalog \
		-b /boot/grub/i386-pc/eltorito.img \
		-no-emul-boot \
		-boot-load-size 4 \
		-boot-info-table \
		--grub2-boot-info \
		-eltorito-alt-boot \
		-e '--interval:appended_partition_2:::' \
		-no-emul-boot \
		.


cidata: $(META_DATA) $(USER_DATA)
	@for dep in $(SEED_DEPS); do \
		command -v $$dep >/dev/null 2>&1 || { echo "'$$dep' is not installed"; exit 1; }; \
	done
	@if [ "$$(id -u)" -ne 0 ]; then \
		echo "This rule must be run as root (sudo make cidata)"; exit 1; \
	fi
	rm -f $(CIDATA)
	dd if=/dev/zero of=$(CIDATA) bs=1024 count=1440 status=none
	mkfs.vfat -n cidata $(CIDATA)

	MNTDIR=$$(mktemp -d /tmp/cidata.XXXXXX) || exit 1; \
	if mount -o loop $(CIDATA) $$MNTDIR; then \
		cp "$(META_DATA)" $$MNTDIR/meta-data && \
		cp "$(USER_DATA)" $$MNTDIR/user-data && \
		test -s $$MNTDIR/meta-data && test -s $$MNTDIR/user-data && sync; \
		rc=$$?; \
		umount $$MNTDIR || rc=1; \
	else \
		echo "Failed to mount $(CIDATA) on $$MNTDIR"; \
		rc=1; \
	fi; \
	rmdir $$MNTDIR 2>/dev/null; \
	[ $$rc -eq 0 ] || { echo "Failed to write seed files into $(CIDATA)"; rm -f $(CIDATA); exit 1; }
	@fsck.fat -nv $(CIDATA) >/dev/null || { echo "Image integrity check FAILED!"; rm -f $(CIDATA); exit 1; }
	@echo "cidata VFAT floppy image created: $(CIDATA)"

clean:
	rm -rf $(ISODIR) $(NEWISO) $(CIDATA)

distclean: clean
	rm -f $(ISO)
